FROM mcr.microsoft.com/dotnet/runtime:8.0-alpine

RUN mkdir -p /app
WORKDIR /app

LABEL org.opencontainers.image.title="unikctl dotnet runtime"
LABEL org.opencontainers.image.source="https://github.com/vizvasanlya/unikctl"
