FROM eclipse-temurin:21-jre-alpine

RUN mkdir -p /app
WORKDIR /app

LABEL org.opencontainers.image.title="unikctl java runtime"
LABEL org.opencontainers.image.source="https://github.com/vizvasanlya/unikctl"
